name: CMS Merge & Deploy

on:
  push:
    branches:
      - dev
      - staging
      - main

permissions:
  contents: write
  id-token: write

jobs:
  merge-dev-to-main:
    if: github.ref_name == 'dev'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Merge dev into main
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: dev
          target_branch: main
          message: Auto-merge dev to main
          github_token: ${{ secrets.GITHUB_TOKEN }}

  deploy-main-from-dev:
    name: Deploy Main after Dev Merge
    if: github.ref_name == 'dev'
    needs: merge-dev-to-main
    runs-on: ubuntu-latest
    env:
      TF_IN_AUTOMATION: true
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Set environment and AMI for main
        id: env-config
        run: |
          echo "environment=prod" >> $GITHUB_OUTPUT
          cho "ami_owner=${{ secrets.PROD_AMI_OWNER }}" >> $GITHUB_OUTPUT
          echo "ami_owner=449630918120" >> $GITHUB_OUTPUT

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/auto-deploy-GitHubActionsRole
          role-session-name: github-actions
          aws-region: ${{ secrets.AWS_REGION || 'us-west-2' }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "~1.0"

      - name: Terraform Init
        working-directory: ./hosting
        run: terraform init -input=false

      - name: Terraform Plan
        working-directory: ./hosting
        run: |
          terraform plan -input=false \
            -var="environment=${{ steps.env-config.outputs.environment }}" \
            -var="custom_ami_owner=${{ steps.env-config.outputs.ami_owner }}" \
            -out=tfplan

      - name: Terraform Apply
        working-directory: ./hosting
        run: terraform apply -auto-approve -input=false tfplan

  deploy-staging:
    if: github.ref_name == 'staging'
    runs-on: ubuntu-latest
    env:
      TF_IN_AUTOMATION: true
    steps:
      - name: Checkout staging branch
        uses: actions/checkout@v4
        with:
          ref: staging

      - name: Set environment and AMI for staging
        id: env-config
        run: |
          echo "environment=staging" >> $GITHUB_OUTPUT
          echo "ami_name=${{ secrets.STAGING_AMI_NAME }}" >> $GITHUB_OUTPUT
          echo "ami_owner=${{ secrets.STAGING_AMI_OWNER }}" >> $GITHUB_OUTPUT

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/auto-deploy-GitHubActionsRole
          role-session-name: github-actions
          aws-region: ${{ secrets.AWS_REGION || 'us-west-2' }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "~1.0"

      - name: Terraform Init
        working-directory: ./hosting
        run: terraform init -input=false

      - name: Terraform Plan
        working-directory: ./hosting
        run: |
          terraform plan -input=false \
            -var="environment=${{ steps.env-config.outputs.environment }}" \
            -var="custom_ami_owner=${{ steps.env-config.outputs.ami_owner }}" \
            -out=tfplan

      - name: Terraform Apply
        working-directory: ./hosting
        run: terraform apply -auto-approve -input=false tfplan

  deploy-main-direct:
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    env:
      TF_IN_AUTOMATION: true
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Set environment and AMI for main
        id: env-config
        run: |
          echo "environment=prod" >> $GITHUB_OUTPUT
          echo "ami_name=${{ secrets.PROD_AMI_NAME }}" >> $GITHUB_OUTPUT
          echo "ami_owner=${{ secrets.PROD_AMI_OWNER }}" >> $GITHUB_OUTPUT

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/auto-deploy-GitHubActionsRole
          role-session-name: github-actions
          aws-region: ${{ secrets.AWS_REGION || 'us-west-2' }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "~1.0"

      - name: Terraform Init
        working-directory: ./hosting
        run: terraform init -input=false

      - name: Terraform Plan
        working-directory: ./hosting
        run: |
          terraform plan -input=false \
            -var="environment=${{ steps.env-config.outputs.environment }}" \
            -var="custom_ami_owner=${{ steps.env-config.outputs.ami_owner }}" \
            -out=tfplan

      - name: Terraform Apply
        working-directory: ./hosting
        run: terraform apply -auto-approve -input=false tfplan

